export const typeMap = {
  request: { dir: "requests", template: "request-card.md" },
  preflight: { dir: "preflight", template: "preflight-report.md" },
  spec: { dir: "specs", template: "spec.md" },
  eval: { dir: "evals", template: "eval.md" },
  task: { dir: "tasks", template: "task-card.md" },
  log: { dir: "ai-logs", template: "ai-task-log.md" },
  "review-packet": { dir: "review-packets", template: "review-packet.md", defaultName: "review-packet" },
  "review-loop-report": { dir: "review-loop-reports", template: "review-loop-report.md", defaultName: "review-loop-report" },
  "gpt-review-prompt": { dir: "gpt-review-prompts", template: "gpt-review-prompt.md", defaultName: "gpt-review-prompt" },
  "adoption-assessment": { dir: ".intentos/adoption", template: "adoption-assessment.md", defaultName: "adoption-assessment" },
  "governance-map": { dir: ".intentos/adoption", template: "existing-governance-map.md", defaultName: "existing-governance-map" },
  "human-status-report": { dir: "status-reports", template: "human-status-report.md", defaultName: "status-report" },
  "decision-brief": { dir: "decision-briefs", template: "decision-brief.md", defaultName: "decision-brief" },
  "plain-review-summary": { dir: "review-summaries", template: "plain-review-summary.md", defaultName: "review-summary" },
  "customer-handoff": { dir: "customer-handoffs", template: "customer-handoff.md", defaultName: "customer-handoff" },
  "follow-up-proposal": { dir: "follow-up-proposals", template: "follow-up-proposal.md", defaultName: "follow-up-proposal" },
  "final-report": { dir: "final-reports", template: "final-report.md", defaultName: "final-report" },
  "goal-card": { dir: "goal-cards", template: "goal-card.md", defaultName: "goal" },
  "subagent-run-plan": { dir: "subagent-run-plans", template: "subagent-run-plan.md", defaultName: "subagent-run-plan" },
  "launch-readiness-report": { dir: "launch-readiness", template: "launch-readiness-report.md", defaultName: "launch-readiness" },
  "launch-review-view": { dir: "launch-review-views", template: "launch-review-view-card.md", defaultName: "launch-review-view" },
  "release-adapter-profile": { dir: "release-adapters", template: "release-adapter-profile.md", defaultName: "release-adapter" },
  "release-guide-card": { dir: "release-guides", template: "release-guide-card.md", defaultName: "release-guide" },
  "platform-release-recipe": { dir: "release-recipes", template: "platform-release-recipe.md", defaultName: "release-recipe" },
  "release-handoff-pack": { dir: "release-handoff-packs", template: "release-handoff-pack.md", defaultName: "release-handoff" },
  "release-approval": { dir: "approval-records", template: "release-approval-record.md", defaultName: "release-approval" },
  "release-execution-plan": { dir: "release-execution-plans", template: "release-execution-plan.md", defaultName: "release-execution" },
  "release-plan": { dir: "release-plans", template: "release-plan.md", defaultName: "release-plan" },
  "conversation-turn-classification": { dir: "conversation-turns", template: "conversation-turn-classification.md", defaultName: "conversation-turn" },
  "scope-change-report": { dir: "scope-change-reports", template: "scope-change-report.md", defaultName: "scope-change" },
  "adoption-trial-report": { dir: "adoption-trial-reports", template: "adoption-trial-report.md", defaultName: "adoption-trial" },
  "real-adoption-trial-report": { dir: "real-adoption-trials", template: "real-adoption-trial-report.md", defaultName: "real-adoption-trial" },
  "patch-classification": { dir: "patch-classifications", template: "patch-classification-report.md", defaultName: "patch-classification" },
  "patch-classification-false-positive": { dir: "patch-classification-false-positives", template: "patch-classification-false-positive.md", defaultName: "patch-classification-false-positive" },
  "workflow-adoption-map": { dir: "workflow-adoption-maps", template: "workflow-adoption-map.md", defaultName: "workflow-adoption-map" },
  "native-migration-plan": { dir: "native-migration-plans", template: "native-migration-plan.md", defaultName: "native-migration" },
  "existing-rule-reconciliation-report": { dir: "existing-rule-reconciliations", template: "existing-rule-reconciliation-report.md", defaultName: "rule-reconciliation" },
  "document-lifecycle-report": { dir: "doc-lifecycle-reports", template: "document-lifecycle-report.md", defaultName: "document-lifecycle" },
  "document-archive-apply-plan": { dir: "archive-apply-plans", template: "document-archive-apply-plan.md", defaultName: "archive-apply" },
  "unified-apply-plan": { dir: "apply-plans", template: "unified-apply-plan.md", defaultName: "apply-plan" },
  "controlled-apply-readiness-report": { dir: "apply-readiness-reports", template: "controlled-apply-readiness-report.md", defaultName: "apply-readiness" },
  "approval-record": { dir: "approval-records", template: "approval-record.md", defaultName: "approval-record" },
  "beginner-entry-card": { dir: "beginner-entry-cards", template: "beginner-entry-card.md", defaultName: "beginner-entry" },
  "conversation-ask-card": { dir: "conversation-ask-cards", template: "conversation-ask-card.md", defaultName: "conversation-ask" },
  "work-queue-report": { dir: "work-queue", template: "work-queue-report.md", defaultName: "work-queue" },
  "hook-orchestration-plan": { dir: "hook-orchestration-plans", template: "hook-orchestration-plan.md", defaultName: "hook-plan" },
  "project-hook-policy": { dir: "hook-policies", template: "project-hook-policy.md", defaultName: "hook-policy" },
  "active-work-thread": { dir: "active-work-threads", template: "active-work-thread.md", defaultName: "active-work-thread" },
  "guided-decision-summary": { dir: "guided-decision-summaries", template: "guided-decision-summary.md", defaultName: "guided-decision" },
  "change-boundary-report": { dir: "change-boundary-reports", template: "change-boundary-report.md", defaultName: "change-boundary" },
  "baseline-state-report": { dir: "baseline-state-reports", template: "baseline-state-report.md", defaultName: "baseline-state" },
  "baseline-pack-selection-report": { dir: "baseline-pack-selections", template: "baseline-pack-selection-report.md", defaultName: "baseline-pack-selection" },
  "standard-baseline-selection-report": { dir: "standard-baseline-selections", template: "standard-baseline-selection-report.md", defaultName: "standard-baseline-selection" },
  "baseline-decision-card": { dir: "baseline-decision-cards", template: "baseline-decision-card.md", defaultName: "baseline-decision" },
  "workflow-guidance-card": { dir: "workflow-guidance-cards", template: "workflow-guidance-card.md", defaultName: "workflow-guidance" },
  "review-surface-card": { dir: "review-surface-cards", template: "review-surface-card.md", defaultName: "review-surface" },
  "change-impact-coverage-report": { dir: "change-impact-coverage-reports", template: "change-impact-coverage-report.md", defaultName: "change-impact-coverage" },
  "delivery-path-report": { dir: "delivery-path-reports", template: "delivery-path-report.md", defaultName: "delivery-path" },
  "debt-knowledge-handoff-report": { dir: "debt-handoff-reports", template: "debt-knowledge-handoff-report.md", defaultName: "debt-handoff" },
  "execution-closure-report": { dir: "execution-closures", template: "execution-closure-report.md", defaultName: "execution-closure" },
  "user-decision-card": { dir: "decision-briefs", template: "user-decision-card.md", defaultName: "user-decision" },
  "control-effectiveness-report": { dir: "control-effectiveness-reports", template: "control-effectiveness-report.md", defaultName: "control-effectiveness" },
  "planning-closure-report": { dir: "planning-closure-reports", template: "planning-closure-report.md", defaultName: "planning-closure" },
};

export const aliases = {
  "ai-log": "log",
  ailog: "log",
  review: "review-packet",
  reviewpacket: "review-packet",
  "review-packets": "review-packet",
  "review-loop": "review-loop-report",
  reviewloop: "review-loop-report",
  reviewloopreport: "review-loop-report",
  "review-loop-reports": "review-loop-report",
  "gpt-review": "gpt-review-prompt",
  gptreview: "gpt-review-prompt",
  gptprompt: "gpt-review-prompt",
  "gpt-review-prompts": "gpt-review-prompt",
  adoption: "adoption-assessment",
  assessment: "adoption-assessment",
  "existing-governance-map": "governance-map",
  status: "human-status-report",
  "status-report": "human-status-report",
  humanstatus: "human-status-report",
  "human-status": "human-status-report",
  decision: "decision-brief",
  "human-decision": "decision-brief",
  "review-summary": "plain-review-summary",
  reviewsummary: "plain-review-summary",
  handoff: "customer-handoff",
  "customer-summary": "customer-handoff",
  followup: "follow-up-proposal",
  "follow-up": "follow-up-proposal",
  proposal: "follow-up-proposal",
  final: "final-report",
  report: "final-report",
  finalreport: "final-report",
  goal: "goal-card",
  goalcard: "goal-card",
  route: "goal-card",
  "goal-mode": "goal-card",
  subagent: "subagent-run-plan",
  subagents: "subagent-run-plan",
  "subagent-run": "subagent-run-plan",
  "subagent-plan": "subagent-run-plan",
  "run-plan": "subagent-run-plan",
  orchestration: "subagent-run-plan",
  launch: "launch-readiness-report",
  "launch-readiness": "launch-readiness-report",
  readiness: "launch-readiness-report",
  "readiness-report": "launch-readiness-report",
  "launch-view": "launch-review-view",
  "launch-review": "launch-review-view",
  "launch-review-view": "launch-review-view",
  "release-review": "launch-review-view",
  "release-adapter": "release-adapter-profile",
  "release-adapter-profile": "release-adapter-profile",
  "release-profile": "release-adapter-profile",
  "release-setup": "release-adapter-profile",
  "beginner-release": "release-adapter-profile",
  "release-guide": "release-guide-card",
  "release-guide-card": "release-guide-card",
  "launch-guide": "release-guide-card",
  "release-path": "release-guide-card",
  "release-recipe": "platform-release-recipe",
  "platform-release-recipe": "platform-release-recipe",
  "platform-recipe": "platform-release-recipe",
  "release-handoff": "release-handoff-pack",
  "release-handoff-pack": "release-handoff-pack",
  "handoff-pack": "release-handoff-pack",
  "release-approval": "release-approval",
  "release-approval-record": "release-approval",
  "structured-release-approval": "release-approval",
  "release-execution": "release-execution-plan",
  "release-execution-plan": "release-execution-plan",
  "release-run": "release-execution-plan",
  "release-plan": "release-plan",
  "release-core-model": "release-plan",
  "release-view": "release-plan",
  "release-summary": "release-plan",
  "conversation-turn": "conversation-turn-classification",
  "conversation-drift": "conversation-turn-classification",
  "turn-classification": "conversation-turn-classification",
  "scope-change": "scope-change-report",
  scopechange: "scope-change-report",
  "first-delivery": "adoption-trial-report",
  walkthrough: "adoption-trial-report",
  "adoption-trial": "adoption-trial-report",
  "adoption-evidence": "adoption-trial-report",
  trial: "adoption-trial-report",
  "real-adoption": "real-adoption-trial-report",
  "real-adoption-trial": "real-adoption-trial-report",
  "real-trial": "real-adoption-trial-report",
  "patch-classification-report": "patch-classification",
  "patch-classifier": "patch-classification",
  "repair-classification": "patch-classification",
  "repair-scale": "patch-classification",
  "patch-false-positive": "patch-classification-false-positive",
  "false-positive": "patch-classification-false-positive",
  "risk-surface-calibration": "patch-classification-false-positive",
  "workflow-map": "workflow-adoption-map",
  "workflow-adapter": "workflow-adoption-map",
  "workflow-adoption": "workflow-adoption-map",
  "adoption-map": "workflow-adoption-map",
  "existing-workflow": "workflow-adoption-map",
  "native-migration": "native-migration-plan",
  "migration-plan": "native-migration-plan",
  "native-migration-plan": "native-migration-plan",
  "existing-project-migration": "native-migration-plan",
  "rule-reconciliation": "existing-rule-reconciliation-report",
  "reconcile-rules": "existing-rule-reconciliation-report",
  "existing-rule-reconciliation": "existing-rule-reconciliation-report",
  "existing-rule-reconciliation-report": "existing-rule-reconciliation-report",
  "doc-lifecycle": "document-lifecycle-report",
  "document-lifecycle": "document-lifecycle-report",
  "document-lifecycle-review": "document-lifecycle-report",
  "docs-lifecycle": "document-lifecycle-report",
  "doc-cleanup": "document-lifecycle-report",
  "archive-suggestion": "document-lifecycle-report",
  "archive-apply": "document-archive-apply-plan",
  "archive-plan": "document-archive-apply-plan",
  "archive-apply-plan": "document-archive-apply-plan",
  "document-archive": "document-archive-apply-plan",
  "document-archive-apply": "document-archive-apply-plan",
  "apply-plan": "unified-apply-plan",
  "unified-apply": "unified-apply-plan",
  "unified-apply-plan": "unified-apply-plan",
  "apply": "unified-apply-plan",
  "write-plan": "unified-apply-plan",
  "apply-readiness": "controlled-apply-readiness-report",
  "controlled-apply": "controlled-apply-readiness-report",
  "controlled-apply-readiness": "controlled-apply-readiness-report",
  "apply-ready": "controlled-apply-readiness-report",
  "apply-readiness-report": "controlled-apply-readiness-report",
  approval: "approval-record",
  "approval-record": "approval-record",
  "human-approval": "approval-record",
  "apply-approval": "approval-record",
  ask: "beginner-entry-card",
  "beginner-entry": "beginner-entry-card",
  "beginner-entry-card": "beginner-entry-card",
  beginner: "beginner-entry-card",
  "user-entry": "beginner-entry-card",
  "conversation-ask": "conversation-ask-card",
  "conversation-native-ask": "conversation-ask-card",
  "conversation-entry": "conversation-ask-card",
  "plain-goal": "conversation-ask-card",
  "work-queue": "work-queue-report",
  "todo": "work-queue-report",
  "todo-list": "work-queue-report",
  "task-queue": "work-queue-report",
  "pause-report": "work-queue-report",
  "resume-plan": "work-queue-report",
  "hook-plan": "hook-orchestration-plan",
  "hook-orchestration": "hook-orchestration-plan",
  "hook-orchestration-report": "hook-orchestration-plan",
  "hooks": "hook-orchestration-plan",
  "automation-hook": "hook-orchestration-plan",
  "hook-policy": "project-hook-policy",
  "project-hook-policy": "project-hook-policy",
  "hook-policy-report": "project-hook-policy",
  "hook-rules": "project-hook-policy",
  "hook-policy-hardening": "project-hook-policy",
  "work-thread": "active-work-thread",
  "active-thread": "active-work-thread",
  "mainline": "active-work-thread",
  parking: "active-work-thread",
  "guided-decision": "guided-decision-summary",
  "decision-summary": "guided-decision-summary",
  "delivery-decision": "guided-decision-summary",
  "decision-delegation": "guided-decision-summary",
  "change-boundary": "change-boundary-report",
  "diff-boundary": "change-boundary-report",
  "boundary-report": "change-boundary-report",
  "baseline-state": "baseline-state-report",
  "baseline-state-review": "baseline-state-report",
  "no-code-baseline": "baseline-state-report",
  "baseline-pack-selection": "baseline-pack-selection-report",
  "baseline-packs": "baseline-pack-selection-report",
  "pack-selection": "baseline-pack-selection-report",
  "baseline-pack": "baseline-pack-selection-report",
  "standard-baseline-selection": "standard-baseline-selection-report",
  "standard-baseline": "standard-baseline-selection-report",
  "standard-pack-selection": "standard-baseline-selection-report",
  "standard-packs": "standard-baseline-selection-report",
  "baseline-decision": "baseline-decision-card",
  "decision-card": "baseline-decision-card",
  "guided-baseline": "baseline-decision-card",
  "guided-baseline-selection": "baseline-decision-card",
  guide: "workflow-guidance-card",
  guidance: "workflow-guidance-card",
  "workflow-guidance": "workflow-guidance-card",
  "workflow-guidance-report": "workflow-guidance-card",
  concierge: "workflow-guidance-card",
  "review-surface": "review-surface-card",
  "review-surface-card": "review-surface-card",
  "review-plan": "review-surface-card",
  "review-scope": "review-surface-card",
  "review-surfaces": "review-surface-card",
  "impact-coverage": "change-impact-coverage-report",
  "change-impact": "change-impact-coverage-report",
  "change-impact-coverage": "change-impact-coverage-report",
  "impact-coverage-report": "change-impact-coverage-report",
  "delivery-path": "delivery-path-report",
  "delivery-state": "delivery-path-report",
  "delivery-path-report": "delivery-path-report",
  "usable-state": "delivery-path-report",
  "useful-use": "delivery-path-report",
  "debt-handoff": "debt-knowledge-handoff-report",
  "handoff-report": "debt-knowledge-handoff-report",
  "knowledge-handoff": "debt-knowledge-handoff-report",
  "debt-register": "debt-knowledge-handoff-report",
  "debt-knowledge-handoff": "debt-knowledge-handoff-report",
  closure: "execution-closure-report",
  "execution-closure": "execution-closure-report",
  "execution-review": "execution-closure-report",
  "execution-review-closure": "execution-closure-report",
  "closure-report": "execution-closure-report",
  "post-execution": "execution-closure-report",
  "commit-readiness": "execution-closure-report",
  "user-decision": "user-decision-card",
  "decision-card-user": "user-decision-card",
  "control-effectiveness": "control-effectiveness-report",
  "control-proof": "control-effectiveness-report",
  "control-effectiveness-report": "control-effectiveness-report",
  "planning-closure": "planning-closure-report",
  "planning-closure-report": "planning-closure-report",
  "execution-entry-contract": "planning-closure-report",
};
